from __future__ import annotations

import json
from pathlib import Path

from scripts.quality_gates.checks import find_missing_spec_references


def _write_manifest(
    root: Path, *, anchor: str = "protocol", prefix: str = "endure/protocol"
) -> None:
    specs = root / "docs" / "specs"
    specs.mkdir(parents=True)
    (specs / "scope.md").write_text("# Scope\n\n## Protocol\n", encoding="utf-8")
    (specs / "module_references.json").write_text(
        json.dumps(
            {
                "rules": [
                    {
                        "path_prefix": prefix,
                        "references": [f"docs/specs/scope.md#{anchor}"],
                    }
                ],
                "schema_version": 1,
            }
        ),
        encoding="utf-8",
    )


def test_spec_references_report_missing_reference(tmp_path: Path) -> None:
    target = tmp_path / "endure" / "protocol" / "example.py"
    target.parent.mkdir(parents=True)
    target.write_text('"""Protocol helper."""\n', encoding="utf-8")

    violations = find_missing_spec_references(
        repo_root=tmp_path, paths=(Path("endure/protocol"),)
    )

    assert len(violations) == 1
    assert "manifest is missing" in violations[0].message


def test_spec_references_accept_existing_reference(tmp_path: Path) -> None:
    target = tmp_path / "endure" / "protocol" / "example.py"
    target.parent.mkdir(parents=True)
    target.write_text('"""Protocol helper (spec §6)."""\n', encoding="utf-8")
    _write_manifest(tmp_path)

    violations = find_missing_spec_references(
        repo_root=tmp_path, paths=(Path("endure/protocol"),)
    )

    assert violations == []


def test_spec_references_reject_missing_heading(tmp_path: Path) -> None:
    target = tmp_path / "endure" / "protocol" / "example.py"
    target.parent.mkdir(parents=True)
    target.write_text('"""Protocol helper (spec §6)."""\n', encoding="utf-8")
    _write_manifest(tmp_path, anchor="missing")

    violations = find_missing_spec_references(
        repo_root=tmp_path, paths=(Path("endure/protocol"),)
    )

    assert len(violations) == 1
    assert "heading does not exist" in violations[0].message


def test_spec_references_skip_autogenerated_migration_versions(tmp_path: Path) -> None:
    target = (
        tmp_path / "endure" / "storage" / "migrations" / "versions" / "0001_init.py"
    )
    target.parent.mkdir(parents=True)
    target.write_text(
        '"""autogenerated by alembic; no spec ref."""\n', encoding="utf-8"
    )

    violations = find_missing_spec_references(
        repo_root=tmp_path, paths=(Path("endure/storage"),)
    )

    assert violations == []
