from __future__ import annotations

from pathlib import Path

from scripts.quality_gates.checks import find_missing_spec_references


def test_spec_references_report_missing_reference(tmp_path: Path) -> None:
    target = tmp_path / "endure" / "protocol" / "example.py"
    target.parent.mkdir(parents=True)
    target.write_text('"""Protocol helper."""\n', encoding="utf-8")

    violations = find_missing_spec_references(
        repo_root=tmp_path, paths=(Path("endure/protocol"),)
    )

    assert len(violations) == 1
    assert "missing a spec reference" in violations[0].message


def test_spec_references_accept_existing_reference(tmp_path: Path) -> None:
    target = tmp_path / "endure" / "protocol" / "example.py"
    target.parent.mkdir(parents=True)
    target.write_text('"""Protocol helper (spec §6)."""\n', encoding="utf-8")

    violations = find_missing_spec_references(
        repo_root=tmp_path, paths=(Path("endure/protocol"),)
    )

    assert violations == []


def test_spec_references_skip_autogenerated_migration_versions(tmp_path: Path) -> None:
    target = (
        tmp_path / "endure" / "storage" / "migrations" / "versions" / "0001_init.py"
    )
    target.parent.mkdir(parents=True)
    target.write_text(
        '"""autogenerated by alembic; no spec ref."""\n', encoding="utf-8"
    )

    violations = find_missing_spec_references(
        repo_root=tmp_path, paths=(Path("endure/storage"),)
    )

    assert violations == []
