from __future__ import annotations

import os
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import Iterator, Sequence

IGNORED_PARTS = {
    ".git",
    ".venv",
    "__pycache__",
    ".pytest_cache",
    ".ruff_cache",
    "node_modules",
}

# Autogenerated Alembic migrations have their own verification suite, so the
# domain guardrails target hand-maintained modules instead.
# Matched by repo-relative prefix only, not by name anywhere in the path
# (which would also reject pytest's /private/var/... tmp dirs).
IGNORED_REPO_RELATIVE_PREFIXES = (Path("endure/storage/migrations/versions"),)


@dataclass(frozen=True)
class Violation:
    path: Path
    line: int
    message: str


def _is_under_ignored_prefix(repo_root: Path, candidate: Path) -> bool:
    try:
        relative = candidate.relative_to(repo_root)
    except ValueError:
        return False
    return any(
        relative == prefix or prefix in relative.parents
        for prefix in IGNORED_REPO_RELATIVE_PREFIXES
    )


def _tracked_files(repo_root: Path) -> tuple[Path, ...] | None:
    """Return the repository's tracked files, or None outside a Git checkout."""
    if not (repo_root / ".git").exists():
        return None
    git = shutil.which("git")
    if git is None:
        return None
    try:
        result = subprocess.run(  # noqa: S603 - resolved Git binary, no shell
            [git, "-C", str(repo_root), "ls-files", "-z"],
            check=True,
            capture_output=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    return tuple(
        repo_root / Path(os.fsdecode(raw_path))
        for raw_path in result.stdout.split(b"\0")
        if raw_path
    )


def iter_text_files(repo_root: Path, entries: Sequence[Path]) -> Iterator[Path]:
    tracked = _tracked_files(repo_root)
    for entry in entries:
        full_path = repo_root / entry
        if full_path.is_file():
            yield full_path
            continue

        if not full_path.is_dir():
            continue

        candidates = (
            sorted(
                path
                for path in tracked
                if path.is_file() and (path == full_path or full_path in path.parents)
            )
            if tracked is not None
            else sorted(path for path in full_path.rglob("*") if path.is_file())
        )
        for candidate in candidates:
            if any(part in IGNORED_PARTS for part in candidate.parts):
                continue
            if _is_under_ignored_prefix(repo_root, candidate):
                continue
            yield candidate


def iter_json_files(repo_root: Path, entries: Sequence[Path]) -> Iterator[Path]:
    for path in iter_text_files(repo_root, entries):
        if path.suffix == ".json":
            yield path


def format_violations(
    title: str, violations: Sequence[Violation], repo_root: Path
) -> str:
    lines = [title]
    for violation in violations:
        try:
            relative_path = violation.path.relative_to(repo_root)
        except ValueError:
            relative_path = violation.path
        lines.append(f"- {relative_path}:{violation.line}: {violation.message}")
    return "\n".join(lines)
