"""Minimal hand-curated bittensor type stub.

Covers only the public surface we use in endure/ and neurons/. Extend as
needed. Primary purpose: catch pre-v10 lowercase-API drift
(bt.wallet -> bt.Wallet etc.) at typecheck time.
"""

from typing import Any

from .utils.btlogging import logging as logging
from . import mock as mock

class Wallet:
    hotkey: Any
    coldkey: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @classmethod
    def add_args(cls, parser: Any) -> None: ...

class Subtensor:
    chain_endpoint: str
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @classmethod
    def add_args(cls, parser: Any) -> None: ...
    def metagraph(self, netuid: int) -> "Metagraph": ...
    def serve_axon(self, *args: Any, **kwargs: Any) -> Any: ...
    def subnet(self, netuid: int, block: int | None = ...) -> "DynamicInfo": ...
    def is_hotkey_registered(self, *args: Any, **kwargs: Any) -> bool: ...
    def get_current_block(self) -> int: ...
    def min_allowed_weights(self, *args: Any, **kwargs: Any) -> int: ...
    def max_weight_limit(self, *args: Any, **kwargs: Any) -> float: ...
    def set_weights(self, *args: Any, **kwargs: Any) -> Any: ...
    def weights(self, netuid: int) -> Any: ...
    def query_module(self, *args: Any, **kwargs: Any) -> Any: ...
    def close(self) -> None: ...

class Metagraph:
    n: Any
    hotkeys: list[Any]
    axons: list[Any]
    uids: Any
    validator_permit: list[bool]
    last_update: list[int]
    S: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def sync(self, *args: Any, **kwargs: Any) -> None: ...

class DynamicInfo:
    tao_in: Any
    alpha_in: Any
    price: Any

class Axon:
    ip: str
    port: int
    external_ip: str
    external_port: int
    wallet: Wallet
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @classmethod
    def add_args(cls, parser: Any) -> None: ...
    def attach(self, *args: Any, **kwargs: Any) -> "Axon": ...
    def serve(self, *args: Any, **kwargs: Any) -> "Axon": ...
    def start(self) -> "Axon": ...
    def stop(self) -> "Axon": ...

class Dendrite:
    keypair: Any
    def __init__(
        self, wallet: Wallet | None = ..., *args: Any, **kwargs: Any
    ) -> None: ...
    # __call__ delegates to aquery: broadcast a synapse to a list of axons.
    async def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    async def forward(self, *args: Any, **kwargs: Any) -> Any: ...
    def preprocess_synapse_for_request(
        self, *args: Any, **kwargs: Any
    ) -> "Synapse": ...

class Synapse:
    # bt.Synapse is an extensible Pydantic model — subclasses add
    # arbitrary fields (dummy_input, dummy_output, ...). Allow any
    # attribute access so pyright doesn't flag scaffold/test subclasses.
    dendrite: Any
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def copy(self) -> "Synapse": ...

class AxonInfo:
    ip: str
    port: int
    is_serving: bool
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

class Config:
    # bt.Config is a dynamic argparse-backed namespace. Let attribute
    # access return Any so callers can read cfg.netuid, cfg.neuron.xxx,
    # cfg.blacklist.xxx, etc. without pyright false positives.
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    # True only when the command line supplied the parameter (not defaulted).
    def is_set(self, param_name: str) -> bool: ...

class MockSubtensor(Subtensor):
    chain_state: dict[str, Any]
    block_number: int
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def force_register_neuron(
        self,
        *,
        netuid: int,
        hotkey_ss58: str,
        coldkey_ss58: str,
        balance: int,
        stake: int,
    ) -> Any: ...
    def create_subnet(self, netuid: int) -> None: ...

# NOTE: bt.MockWallet does NOT exist in v10.x. Use bittensor_wallet.mock.get_mock_wallet
# NOTE: bt.wallet/subtensor/metagraph/dendrite/axon lowercase names do NOT exist
